# Generated by Django 5.0.3 on 2026-03-30 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-created_at"]},
        ),
    ]
