version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: b2b_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=b2b_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass

  redis:
    image: redis:7-alpine
    container_name: b2b_redis

  web:
    build: .
    container_name: b2b_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=b2b_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
  worker:
    build: .
    container_name: b2b_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=b2b_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - REDIS_URL=redis://redis:6379/0
volumes:
  postgres_data:
